spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: config-server-dev1
---
spring:
    profiles: test
    application:
        name: config-server-test
